version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.3.0
      environment:
        TZ: /usr/share/zoneinfo/Asia/Tokyo
  working_directory: ~/repo

aliases:
  - &restore_cache
      keys:
        - v2-dependencies-{{ checksum "package.json" }}
        - v2-dependencies-
  - &save_cache
      paths:
        - node_modules
      key: v2-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn install
      - run: yarn build
      - save_cache: *save_cache
